New-Item -Path "HKCU:\Software\UAT_HealthCheck_Automation" -Force | Out-Null
Set-ItemProperty -Path "HKCU:\Software\UAT_HealthCheck_Automation" -Name "AccountNo" -Value "210116477"
Set-ItemProperty -Path "HKCU:\Software\UAT_HealthCheck_Automation" -Name "LoginPassword" -Value "dirbitest"
Set-ItemProperty -Path "HKCU:\Software\UAT_HealthCheck_Automation" -Name "TradingPassword" -Value "dirbitest"
Set-ItemProperty -Path "HKCU:\Software\UAT_HealthCheck_Automation" -Name "StockCode_1" -Value "5940"
Set-ItemProperty -Path "HKCU:\Software\UAT_HealthCheck_Automation" -Name "NumberOfShares_1" -Value "100"
Set-ItemProperty -Path "HKCU:\Software\UAT_HealthCheck_Automation" -Name "ExecutionCondtion_1" -Value "577"
Set-ItemProperty -Path "HKCU:\Software\UAT_HealthCheck_Automation" -Name "ChildExecutionCondtion_1" -Value "100"
Set-ItemProperty -Path "HKCU:\Software\UAT_HealthCheck_Automation" -Name "StockCode_2" -Value "5940"
Set-ItemProperty -Path "HKCU:\Software\UAT_HealthCheck_Automation" -Name "NumberOfShares_2" -Value "100"
Set-ItemProperty -Path "HKCU:\Software\UAT_HealthCheck_Automation" -Name "ExecutionCondtion_2" -Value "577"
Set-ItemProperty -Path "HKCU:\Software\UAT_HealthCheck_Automation" -Name "ChildExecutionCondtion_2" -Value "100"
Set-ItemProperty -Path "HKCU:\Software\UAT_HealthCheck_Automation" -Name "WebPageURL" -Value "http://172.16.112.142:9601/webbroker3/44/pc/WEB3AccountLogin.jsp"
